MODEL:
  WEIGHTS: "./ckpt/init_stu_res50_tea_res101.pth"
  META_ARCHITECTURE: "CondInst_distill"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MAX_PROPOSALS: 500
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  find_unused_parameters: True
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FILE_CLIENT: !!python/object/apply:eval [ "[dict(
        backend='petrel',
        path_mapping=dict({
            'datasets/coco/': 'openmmlab:s3://openmmlab/datasets/detection/coco/',
            '.datasets/coco/': 'openmmlab:s3://openmmlab/datasets/detection/coco/'
        }))]" ]
OUTPUT_DIR: "output/condinst_MS_R_50_1x_distill"
